try {
  console.log(3 / 0);
} catch (error) {
  console.log(error.message);
}
